name: Automerge-repo
description: Open a bug report about automerge-repo
title: "[Bug]: "
type: bug
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an issue!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      value: "It doesn't work"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      value: "It should work"
    validations:
      required: true
  - type: input
    id: automerge-repo-version
    attributes:
      label: What version of automerge-repo are you using?
      value: "It's probably not important and I don't feel like looking it up"
    validations:
      required: true
  - type: dropdown
    id: env
    attributes:
      label: What environment are you seeing the problem in?
      options:
        - Unknown
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - node
        - deno
        - bun
        - Other
      default: 0
    validations:
      required: true
