name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - package.json

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  check-version:
    name: Check for a version change
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.version.outputs.changed }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Detect version change
        id: version
        uses: ./.github/actions/detect-version-change
        with:
          before: ${{ github.event.before }}
          after: ${{ github.sha }}

  publish-docs:
    name: Publish docs
    needs: check-version
    if: needs.check-version.outputs.changed == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Build docs
        run: pnpm exec typedoc

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs

      - name: Deploy docs
        id: deployment
        uses: actions/deploy-pages@v5
