name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    types:
      [
        opened,
        edited,
        synchronize,
        reopened,
        ready_for_review,
        review_requested,
      ]
    branches:
      - main
jobs:
  run-tests:
    if: github.event.pull_request.draft == false
    name: Lint Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install
        run: |
          pnpm install
      - name: Lint
        run: pnpm lint
