name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    types:
      [
        opened,
        edited,
        synchronize,
        reopened,
        ready_for_review,
        review_requested,
      ]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-tests:
    if: github.event.pull_request.draft == false
    name: Lint Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - name: Install and Build
        run: |
          pnpm install
          pnpm build
      - name: Lint
        run: pnpm lint
